language: go
go:
  - 1.9.2
before_script:
  - go get -u github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - gocov test ./... | gocov-xml > coverage.xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
